---
- set_fact:
    repo: '{{ repo_prod.0 }}'
    instance: '{{ repo_prod.1 }}'

- set_fact:
    runner_instance_name:  '{{ ansible_hostname }}-{{ instance }}'
    repo_install_dir: '{{ runners_install_dir }}/repos/{{ runners_owner }}/{{ repo.name }}-{{ instance }}'

# copy files to repo_install_dir
- name: check={{ repo_install_dir }}
  stat:
    path: '{{ repo_install_dir }}'
  changed_when: False
  register: cache_dir
- when: not cache_dir.stat.exists
  block:
      - name: mkdir={{ repo_install_dir }}
        file:
          path: '{{ repo_install_dir }}'
          state: directory
          mode: 0755
      - name: copy src={{ runners_install_cache_dir }}, dest={{ repo_install_dir }}
        synchronize:
          src: '{{ runners_install_cache_dir }}/'
          dest: '{{ repo_install_dir }}/'

- include_tasks: services.yml
  when: not runners_install_only
